### ISSUE TITLE
Show identifier for hidden objectives

### ISSUE THREAD

**Issue by Pablete1234** [OvercastCommunity/Bingo#1]
Currently hidden objectives show just a masked text, would be nice if they showed some way of players referring to them. Atm the best way is "second column 3rd one" or something similar. Could show like `A1- [magic letters]` instead

**Comment by Pugzy** [comment]
Resolved in https://github.com/OvercastCommunity/Bingo/commit/149fb48ef9fb1095c17250c7efd7cbe76e4db071.
