### ISSUE TITLE
Show progress for long-running objectives

### ISSUE THREAD

**Issue by Pablete1234** [OvercastCommunity/Bingo#2]
Objectives that are stateful and carry across matches were often met with confusion, as players were like "i did this previous match and didn't get it, but now i did", simply coming from not properly conveying that both previous match AND current match actions were overall needed.

To keep the info vague and not spoil exactly how many things are needed, proposal is to show a rounded percentage, so instead of `Progress 1/8` we show `Progress ~10%` (ie: rounded to nearest 10 percent, because showing 12.5% would also probably give away that it's 8 or a multiple of 8).

**Comment by Pugzy** [comment]
Resolved in https://github.com/OvercastCommunity/Bingo/commit/b72be0aa756b5d895b727a730c2338599b3ff071.
